// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"

	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CiliumGatewayAuthPoliciesGetter has a method to return a CiliumGatewayAuthPolicyInterface.
// A group's client should implement this interface.
type CiliumGatewayAuthPoliciesGetter interface {
	CiliumGatewayAuthPolicies(namespace string) CiliumGatewayAuthPolicyInterface
}

// CiliumGatewayAuthPolicyInterface has methods to work with CiliumGatewayAuthPolicy resources.
type CiliumGatewayAuthPolicyInterface interface {
	Create(ctx context.Context, ciliumGatewayAuthPolicy *ciliumiov2alpha1.CiliumGatewayAuthPolicy, opts v1.CreateOptions) (*ciliumiov2alpha1.CiliumGatewayAuthPolicy, error)
	Update(ctx context.Context, ciliumGatewayAuthPolicy *ciliumiov2alpha1.CiliumGatewayAuthPolicy, opts v1.UpdateOptions) (*ciliumiov2alpha1.CiliumGatewayAuthPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ciliumGatewayAuthPolicy *ciliumiov2alpha1.CiliumGatewayAuthPolicy, opts v1.UpdateOptions) (*ciliumiov2alpha1.CiliumGatewayAuthPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ciliumiov2alpha1.CiliumGatewayAuthPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*ciliumiov2alpha1.CiliumGatewayAuthPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ciliumiov2alpha1.CiliumGatewayAuthPolicy, err error)
	CiliumGatewayAuthPolicyExpansion
}

// ciliumGatewayAuthPolicies implements CiliumGatewayAuthPolicyInterface
type ciliumGatewayAuthPolicies struct {
	*gentype.ClientWithList[*ciliumiov2alpha1.CiliumGatewayAuthPolicy, *ciliumiov2alpha1.CiliumGatewayAuthPolicyList]
}

// newCiliumGatewayAuthPolicies returns a CiliumGatewayAuthPolicies
func newCiliumGatewayAuthPolicies(c *CiliumV2alpha1Client, namespace string) *ciliumGatewayAuthPolicies {
	return &ciliumGatewayAuthPolicies{
		gentype.NewClientWithList[*ciliumiov2alpha1.CiliumGatewayAuthPolicy, *ciliumiov2alpha1.CiliumGatewayAuthPolicyList](
			"ciliumgatewayauthpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ciliumiov2alpha1.CiliumGatewayAuthPolicy { return &ciliumiov2alpha1.CiliumGatewayAuthPolicy{} },
			func() *ciliumiov2alpha1.CiliumGatewayAuthPolicyList {
				return &ciliumiov2alpha1.CiliumGatewayAuthPolicyList{}
			},
		),
	}
}
