// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumGatewayAuthPolicyLister helps list CiliumGatewayAuthPolicies.
// All objects returned here must be treated as read-only.
type CiliumGatewayAuthPolicyLister interface {
	// List lists all CiliumGatewayAuthPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.CiliumGatewayAuthPolicy, err error)
	// CiliumGatewayAuthPolicies returns an object that can list and get CiliumGatewayAuthPolicies.
	CiliumGatewayAuthPolicies(namespace string) CiliumGatewayAuthPolicyNamespaceLister
	CiliumGatewayAuthPolicyListerExpansion
}

// ciliumGatewayAuthPolicyLister implements the CiliumGatewayAuthPolicyLister interface.
type ciliumGatewayAuthPolicyLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.CiliumGatewayAuthPolicy]
}

// NewCiliumGatewayAuthPolicyLister returns a new CiliumGatewayAuthPolicyLister.
func NewCiliumGatewayAuthPolicyLister(indexer cache.Indexer) CiliumGatewayAuthPolicyLister {
	return &ciliumGatewayAuthPolicyLister{listers.New[*ciliumiov2alpha1.CiliumGatewayAuthPolicy](indexer, ciliumiov2alpha1.Resource("ciliumgatewayauthpolicy"))}
}

// CiliumGatewayAuthPolicies returns an object that can list and get CiliumGatewayAuthPolicies.
func (s *ciliumGatewayAuthPolicyLister) CiliumGatewayAuthPolicies(namespace string) CiliumGatewayAuthPolicyNamespaceLister {
	return ciliumGatewayAuthPolicyNamespaceLister{listers.NewNamespaced[*ciliumiov2alpha1.CiliumGatewayAuthPolicy](s.ResourceIndexer, namespace)}
}

// CiliumGatewayAuthPolicyNamespaceLister helps list and get CiliumGatewayAuthPolicies.
// All objects returned here must be treated as read-only.
type CiliumGatewayAuthPolicyNamespaceLister interface {
	// List lists all CiliumGatewayAuthPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.CiliumGatewayAuthPolicy, err error)
	// Get retrieves the CiliumGatewayAuthPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2alpha1.CiliumGatewayAuthPolicy, error)
	CiliumGatewayAuthPolicyNamespaceListerExpansion
}

// ciliumGatewayAuthPolicyNamespaceLister implements the CiliumGatewayAuthPolicyNamespaceLister
// interface.
type ciliumGatewayAuthPolicyNamespaceLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.CiliumGatewayAuthPolicy]
}
